title:          Robins AFB Aero Club
description:    Unofficial collection of Robins AFB Aero Club information
url:            http://aviation.digivation.net/
owner:
  name:         RAFB Aero Club
  avatar:       
  bio:          "Loves flying"
  email:        matthew@digivation.net

links:
 - title: Online Flight Scheduling
   url: http://www.flightschedulepro.com/
   external: true
 - title: RAFB Aero Club Offical Site
   url: http://www.robinsfss.com/aeroclub.html
   external: true

timezone:       America/New_York
future:         true
pygments:       true
markdown: rdiscount


pagination: 20

permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
