title:          Robins AFB Aero Club
description:    Unofficial collection of Robins AFB Aero Club information
url:            http://localhost:4000
owner:
  name:         RAFB Aero Club
  avatar:       avatar.jpg
  bio:          "Loves flying"
  email:        matthew@digivation.net

links:
 - title: Test New
   url: /index.html
 - title: RAFB Aero Club Offical Site
   url: http://www.robinsfss.com/aeroclub.html
   external: true

timezone:       America/New_York
future:         true
pygments:       true
markdown: rdiscount


pagination: 20

permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
